export const SUBSCRIPTIONS_MODULE_OPTIONS = '¥SUBSCRIPTIONS_MODULE_OPTIONS';
export const METADATA_REALTIME = '¥realtime';
export const SUBSCRIPTIONS_HANDLER_METADATA = '¥SUBSCRIPTIONS_HANDLER_METADATA';
