# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - run: npm ci

      - run: npx nx workspace-lint --base origin/master
      - run: npx nx format:check --base origin/master
      - run: npx nx affected --base=origin/master --target=lint --parallel=3
      - run: npx nx affected --base=origin/master --target=test --parallel=3 --ci --code-coverage
      # build step needs to be configured locally for all platforms (run in parallel?) instead of using EAS (expo acct)
      # - run: npx nx affected --base=origin/master --target=build --parallel=3
